---
title: "dispersion-model"
author: "Britt"
date: "2026-09-17"
output: html_document
---

Determine the dispersion parameter (how over-dispersed is the data?)

```{r}
library(edgeR)

counts.matrix.PM <- PM.counts %>% as.matrix()

#remove unassigned row
counts.matrix.PM <- counts.matrix.PM[, -21]

counts.matrix.PM
```

```{r}
dge.data <- DGEList(counts=counts.matrix.PM, 
                    group=sample.description$group)
dim(dge.data) 
dge.data <- calcNormFactors(dge.data, method = "TMM")
dge.data$samples # look at the normalization factors
```

(make ordination here)


Fit a statistical model for gene expression as a function of experimental parameters.




```{r}
# Ensure levels are set correctly
sample.description$myc <- relevel(factor(sample.description$myc), ref = "NM")
sample.description$trt <- relevel(factor(sample.description$trt), ref = "C")
```


```{r}
#sample.description is the original descriptive dataset (describes our samples but doesn't have counts data)

interaction.design <- model.matrix(~myc*trt,data = sample.description)
rownames(interaction.design) <- sample.description$sample
interaction.design
```
```{r}
# Modern, clean workflow for the Interaction model
dge.data <- estimateDisp(dge.data, interaction.design)

# View the dispersion estimates
summary(dge.data$tagwise.dispersion)
```



```{r}
# 1. Fit using the QL model instead of glmFit
fit <- glmQLFit(dge.data, interaction.design)

# 2. Test using the QL F-test instead of glmLRT
# Treatment Effect
trt.qlf <- glmQLFTest(fit, coef = "trtT")

# Mycorrhization Effect (spM)
myc.qlf <- glmQLFTest(fit, coef = "mycM")

# Interaction Effect (The Synergy)
interaction.qlf <- glmQLFTest(fit, coef = "mycM:trtT")
```
